import NavBare from "@/components/common/NavBare";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sondley",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>

      <NavBare />
      {children}
    </>
  );
}
